name: CI/CD - deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install serverless
        run: |
          python -m pip install --upgrade pip
          pip install serverless
          npm install -g serverless

      - name: Install requirements
        run: pip install -r requirements.txt || true

      - name: Deploy (Serverless)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
          SNS_TOPIC_ARN: ${{ secrets.SNS_TOPIC_ARN }}
        run: npx serverless deploy --stage prod
